version: '3.8'
services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=1d47cc0494a205f4b3bfc2c019916787651f6e7c7945a3b7422b283202ff1f62
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_API_ID=your_api_id
      - TELEGRAM_API_HASH=your_api_hash
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  mongo_data:
